### ISSUE TITLE
Missing permition request 

### ISSUE THREAD

**Issue by vitabr** [googlesamples/android-BluetoothLeGatt#52]
Hi, i just run project on Android 7 and it didn't work( didn't show any ~BLE devices during scan) because of Binder exception:
`W/Binder: Caught a RuntimeException from the binder stub implementation.
                                                                             java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
                                                                                 at android.os.Parcel.readException(Parcel.java:1620)
                                                                                 at android.os.Parcel.readException(Parcel.java:1573)
                                                                                 at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:883)
                                                                                 at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onClientRegistered(BluetoothLeScanner.java:375)
                                                                                 at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:56)
                                                                                 at android.os.Binder.execTransact(Binder.java:453)`

After manually adding of :
`<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`
and manually turning on location permission  thru app settings, application started to work and show BLE devices around.

**Comment by vitabr** [comment]
Conclusion, project missing Android permission check for Android 7+

**Comment by gmelcer** [comment]
Here is the source code with the manifest file fixed and the request to access permissions in the onCreate(). 
[android-BluetoothLeGatt-master 2.zip](https://github.com/googlesamples/android-BluetoothLeGatt/files/1911007/android-BluetoothLeGatt-master.2.zip)

**Comment by Automateme2** [comment]
Thanks for that fix, I'm a newbie trying to get my head around BLE data transfer.  This has helped a lot!

Awesome!

**Comment by olix86** [comment]
Had the same issue and that fixed it, thanks a lot :)

**Comment by stuartsoft** [comment]
GOOGLE. My dude. Please freaking fix your project and add: `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`

**Comment by biafra23** [comment]
> GOOGLE. My dude. Please freaking fix your project and add: `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`

Adding the permission will not be enough, because this is a runtime permission and the target SDK  is 27. They either have to lower the targetSDKVersion or add some code to ask for this runtime permission.
